# docker compose -p marketplace-prod -f compose-prod.yaml up -d

# docker compose -p marketplace-prod -f compose-prod.yaml up --build -d

# docker compose -p marketplace-prod -f compose-prod.yaml build --no-cache catalog_api
# docker compose -p marketplace-prod -f compose-prod.yaml build --no-cache basket_api

# docker compose -p marketplace-prod -f compose-prod.yaml down -v

services:
  catalog_db_prod:
    container_name: "catalog_db_prod"
    image: "postgres:18.1"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456789
    - POSTGRES_DB=catalog_db_prod
    restart: always
    ports:
      - "9301:5432"
    volumes:
      - postgres_catalog_prod:/var/lib/postgresql
    networks:
      - marketplace-prod-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  catalog_api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: cmd/catalog/Dockerfile
    ports:
      - "9201:7001"
    networks:
      - marketplace-prod-net
    environment:
      - CATALOG_APP_PORT=7001
      - CATALOG_PG_HOST=catalog_db_prod
      - CATALOG_PG_PORT=5432
      - CATALOG_PG_DATABASE=catalog_db_prod
      - CATALOG_PG_USER=postgres
      - CATALOG_PG_PASSWORD=123456789
      - CATALOG_PG_SSLMODE=disable
      # file://../../migrations/catalog
      - CATALOG_MIGRATIONS_PATH=file:///app/migrations/catalog
    depends_on:
      catalog_db_prod:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:7001/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  basket_db_prod:
    container_name: "basket_db_prod"
    image: "postgres:18.1"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456789
    - POSTGRES_DB=basket_db_prod
    restart: always
    ports:
      - "9302:5432"
    volumes:
      - postgres_basket_prod:/var/lib/postgresql
    networks:
      - marketplace-prod-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  basket_cache_redis_prod:
    container_name: basket-redis-prod
    image: redis:7
    command: redis-server --requirepass "123456789" --protected-mode no
    restart: always
    ports:
      - "9312:6379"
    volumes:
      - redis_basket_prod:/data
    networks:
      - marketplace-prod-net

  basket_api:
    container_name: basket-api
    build:
      context: .
      dockerfile: cmd/basket/Dockerfile
    ports:
      - "9202:7002"
    networks:
      - marketplace-prod-net
    environment:
      - BASKET_APP_PORT=7002
      - BASKET_DATABASE_URL=postgres://postgres:123456789@basket_db_prod:5432/basket_db_prod?sslmode=disable
      - BASKET_MIGRATIONS_PATH=file:///app/migrations/basket
      - BASKET_REDIS_URL=basket_cache_redis_prod:6379
      - BASKET_REDIS_PASSWORD=123456789
    depends_on:
      basket_db_prod:
        condition: service_healthy
      basket_cache_redis_prod:
        condition: service_started

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:7002/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

volumes:
    postgres_catalog_prod:
    postgres_basket_prod:
    redis_basket_prod:

networks: 
  marketplace-prod-net:
    driver: bridge