syntax = "proto3";

option go_package = "github.com/eavehh/marketpl.microserv/internal/promotion/grpc/pb";

package promotion;

service PromotionService{
    rpc GetPromoByCatalogItem(GetPromoByCatalogItemRequest) returns(GetPromoByCatalogItemResponse);
    rpc CreatePromo(CreatePromoRequest) returns(CreatePromoResponse);
}

message GetPromoByCatalogItemRequest{
    string catalog_item_id = 1;
}

message GetPromoByCatalogItemResponse{
    Promotion promotion = 1;
}

message CreatePromoRequest{
    string catalog_item_id=1;
    string title =2;
    string value =3;
}message CreatePromoResponse{
    string id=1;
    bool success=2;
    string description=3;
}

message Promotion{
    string id = 1;
    string catalog_item_id =2;
    string title =3;
    string value = 4;
}